--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 6.6.5.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 7/18/2024 11:33:43 AM
-- Server version: 15.00.4375
--


SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
USE master
GO

IF DB_NAME() <> N'master' SET NOEXEC ON

--
-- Create database [dblab]
--
PRINT (N'Create database [dblab]')
GO
CREATE DATABASE dblab
ON PRIMARY(
    NAME = N'dblab',
    FILENAME = N'/var/opt/mssql/data/dblab.mdf',
    SIZE = 8192KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
)
LOG ON(
    NAME = N'dblab_log',
    FILENAME = N'/var/opt/mssql/data/dblab_log.ldf',
    SIZE = 8192KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
)
GO

--
-- Alter database
--
PRINT (N'Alter database')
GO
ALTER DATABASE dblab
  SET
    ANSI_NULL_DEFAULT OFF,
    ANSI_NULLS OFF,
    ANSI_PADDING OFF,
    ANSI_WARNINGS OFF,
    ARITHABORT OFF,
    AUTO_CLOSE OFF,
    AUTO_CREATE_STATISTICS ON,
    AUTO_SHRINK OFF,
    AUTO_UPDATE_STATISTICS ON,
    AUTO_UPDATE_STATISTICS_ASYNC OFF,
    COMPATIBILITY_LEVEL = 150,
    CONCAT_NULL_YIELDS_NULL OFF,
    CURSOR_CLOSE_ON_COMMIT OFF,
    CURSOR_DEFAULT GLOBAL,
    DATE_CORRELATION_OPTIMIZATION OFF,
    DB_CHAINING OFF,
    HONOR_BROKER_PRIORITY OFF,
    MULTI_USER,
    NUMERIC_ROUNDABORT OFF,
    PAGE_VERIFY CHECKSUM,
    PARAMETERIZATION SIMPLE,
    QUOTED_IDENTIFIER OFF,
    READ_COMMITTED_SNAPSHOT OFF,
    RECOVERY FULL,
    RECURSIVE_TRIGGERS OFF,
    TRANSFORM_NOISE_WORDS = OFF,
    TRUSTWORTHY OFF
    WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE dblab
  SET ENABLE_BROKER
GO

ALTER DATABASE dblab
  SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

EXECUTE sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO
EXECUTE sp_configure 'nested triggers', 1;
GO
RECONFIGURE;
GO

ALTER DATABASE dblab
  SET QUERY_STORE = OFF
GO

USE dblab
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE dblab
GO

IF DB_NAME() <> N'dblab' SET NOEXEC ON
GO

--
-- Create table [dbo].[users]
--
PRINT (N'Create table [dbo].[users]')
GO
CREATE TABLE dbo.users (
  user_id uniqueidentifier NOT NULL,
  address varchar(255) NULL,
  birth_date datetime2(6) NOT NULL,
  email varchar(255) NULL,
  fname varchar(255) NOT NULL,
  gender varchar(255) NULL,
  lname varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  phone_number varchar(255) NULL,
  username varchar(255) NOT NULL,
  PRIMARY KEY CLUSTERED (user_id),
  CONSTRAINT UKr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[sales_assistant]
--
PRINT (N'Create table [dbo].[sales_assistant]')
GO
CREATE TABLE dbo.sales_assistant (
  staff_id uniqueidentifier NOT NULL,
  address varchar(255) NULL,
  birth_date datetime2(6) NOT NULL,
  email varchar(255) NULL,
  fname varchar(255) NOT NULL,
  gender varchar(255) NULL,
  lname varchar(255) NOT NULL,
  phone_number varchar(255) NULL,
  salary int NOT NULL,
  PRIMARY KEY CLUSTERED (staff_id)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[purchase_assistant]
--
PRINT (N'Create table [dbo].[purchase_assistant]')
GO
CREATE TABLE dbo.purchase_assistant (
  staff_id uniqueidentifier NOT NULL,
  address varchar(255) NULL,
  birth_date datetime2(6) NOT NULL,
  email varchar(255) NULL,
  fname varchar(255) NOT NULL,
  gender varchar(255) NULL,
  lname varchar(255) NOT NULL,
  phone_number varchar(255) NULL,
  salary int NOT NULL,
  PRIMARY KEY CLUSTERED (staff_id)
)
ON [PRIMARY]
GO

-- 
-- Dumping data for table users
--
PRINT (N'Dumping data for table users')
INSERT dbo.users VALUES ('92cdf5eb-a464-4d74-be83-24da0259eb29', 'test', '2024-07-10 03:30:00.0000000', NULL, 'test', 'Male', 'test', '$2a$10$9qlfcncIw3ElQ.wQc4Z54OT126sZPF4WM15p6eCMS.fikfx8WANGW', '09354789654', 'test')
INSERT dbo.users VALUES ('be2651e9-df10-4d5e-8520-9296e4b7b4b7', 'Tehran', '2017-06-06 04:30:00.0000000', 'Aidin@gmail.com', 'Aidin', 'Male', 'Azizi', '$2a$10$BCx0b.ALEjjdOgpxG2sJD.6ddcHFJrM34EOVwgRiHi9TNQOrZ5ri6', '09387459654', 'Aidin')
INSERT dbo.users VALUES ('ce0349bf-30cd-45e2-a9b6-a1d7657bb2b5', 'Qazvin', '2024-07-16 03:30:00.0000000', 'Asal@gmail.com', 'Asal', 'Female', 'Feizi', '$2a$10$ekcB6R1n1O3kZ0PzCcqdT.OeILIKZ3q65Fq81SejKxej0o9raPp3a', '09387456214', 'Asal')
INSERT dbo.users VALUES ('4fb41d62-85a4-4a28-8d96-e4b03dbaf812', 'Karaj', '2024-07-06 03:30:00.0000000', 'Ali@gmail.com', 'Ali', 'Male', 'NasehAhadi', '$2a$10$wTpv6q8bq.NzYnm9oCZfvehhYbwNz883ELukNRU6DkLYYXeU2nTeC', '09106457845', 'Ali')
GO

-- 
-- Dumping data for table sales_assistant
--
PRINT (N'Dumping data for table sales_assistant')
INSERT dbo.sales_assistant VALUES ('c7390e59-aeba-4039-bd87-3126110e0729', 'Tehran', '2024-07-18 08:02:41.6600000', 'Rosa@gmail.com', 'Rosa', 'Female', 'Rostami', '09384756213', 78950000)
INSERT dbo.sales_assistant VALUES ('7b8ea51f-5d0a-4724-ae25-39bce9bcab84', 'Varamin', '1996-02-29 03:30:00.0000000', 'Jalal@gmail.com', 'Jalal', 'Male', 'Hoseini', '09365478245', 28950000)
INSERT dbo.sales_assistant VALUES ('dd4f77f9-4867-4cfb-ba18-f28c2dc005f5', 'Esfahan', '2024-07-06 03:30:00.0000000', 'Sajjad@gmail.com', 'Sajjad', 'Male', 'Moghada', '09109999999', 2570000)
GO

-- 
-- Dumping data for table purchase_assistant
--
PRINT (N'Dumping data for table purchase_assistant')
INSERT dbo.purchase_assistant VALUES ('7e8ba96d-b43d-480e-bd2d-91b08490a7c9', 'Kerman', '2024-07-18 07:59:56.5466670', 'Hosein@gmail.com', 'Hoseini', 'Male', 'Sadooghi', '0902145702', 22000000)
INSERT dbo.purchase_assistant VALUES ('8b1d3866-b596-458e-9a38-9ec6ac08d975', 'Hemedam', '2024-07-18 08:01:13.4000000', 'MohammadA@gmail.com', 'Mohammad', 'Male', 'AghaMohammad', '0902741252', 890000)
INSERT dbo.purchase_assistant VALUES ('7134c493-793e-40d9-87f9-a0fb1e2452f5', 'Darbamd', '2024-07-02 03:30:00.0000000', 'Razieh@gmail.com', 'Razieh', 'Female', 'Vahdat', '09387198078', 28400000)
GO
SET NOEXEC OFF
GO